networks:
  internal:
    driver: bridge


volumes:
  db_itm:


services:
  db_itm:
    image: mysql:8.0.43
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: itm
      MYSQL_USER: itm
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - db_itm:/var/lib/mysql
    networks:
      - internal
